page_404_url: "public/404.html"
per_page: 10
category:
  categories: "Categories"
  per_page: 10
  name_max_length: 255
user:
  size_gavata: 50
  per_page: 20
book:
  per_page: 10 
  size_small: "250x250"
  size_big: 350
  name_max_length: 255
  image_max_size: 5242880
  description_max_length: 1000
  image_accept: "image/jpeg,image/gif,image/png"
request:
  per_page: 10
  area_rows: 3
users:
  avatar: "http://gravatar.com/emails"
mark:
  size_small: "30x30"
  favorate: "favorate"
  unfavorate: "unfavorate"
  read: "read"
  reading: "reading"
  image_reading: "books/reading.png"
  image_read: "books/read.jpg"
